C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\pydantic\_internal\_config.py:383: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)
C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\pydantic\_internal\_config.py:383: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)
INFO:     Started server process [27396]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:8001 (Press CTRL+C to quit)
INFO:     127.0.0.1:56619 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:56620 - "POST /api/embed HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\fastapi\applications.py", line 1134, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\starlette\routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\starlette\routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\starlette\routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\fastapi\routing.py", line 124, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\fastapi\routing.py", line 110, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\fastapi\routing.py", line 390, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\fastapi\routing.py", line 289, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\app\api\embed.py", line 84, in create_embed_endpoint
    await crud_create_embed(session, embed_token=token, cypher_query=request.cypherQuery.strip(), expires_at=expires_at)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\app\db\crud.py", line 18, in create_embed
    await session.commit()
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 1000, in commit
    await greenlet_spawn(self.sync_session.commit)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2030, in commit
    trans.commit(_to_root=True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<string>", line 2, in commit
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1311, in commit
    self._prepare_impl()
    ~~~~~~~~~~~~~~~~~~^^
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1286, in _prepare_impl
    self.session.flush()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4331, in flush
    self._flush(objects)
    ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4466, in _flush
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4427, in _flush
    flush_context.execute()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.mapper,
        ^^^^^^^^^^^^
        uow.states_for_mapper_hierarchy(self.mapper, False, False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        uow,
        ^^^^
    )
    ^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 68, in save_obj
    ) in _organize_states_for_save(base_mapper, states, uowtransaction):
         ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 223, in _organize_states_for_save
    for state, dict_, mapper, connection in _connections_for_states(
                                            ~~~~~~~~~~~~~~~~~~~~~~~^
        base_mapper, uowtransaction, states
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ):
    ^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1759, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
  File "<string>", line 2, in connection
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1037, in connection
    return self._connection_for_bind(bind, execution_options)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1173, in _connection_for_bind
    conn = self._parent._connection_for_bind(
        bind, execution_options
    )
  File "<string>", line 2, in _connection_for_bind
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1187, in _connection_for_bind
    conn = bind.connect()
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3277, in connect
    return self._connection_cls(self)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 143, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3301, in raw_connection
    return self.pool.connect()
           ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 447, in connect
    return _ConnectionFairy._checkout(self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 711, in checkout
    rec = pool._do_get()
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 175, in _do_get
    return self._create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 388, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 673, in __init__
    self.__connect()
    ~~~~~~~~~~~~~~^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 899, in __connect
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 895, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\engine\create.py", line 661, in connect
    return dialect.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 629, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 955, in connect
    await_only(creator_fn(*arg, **kw)),
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\asyncpg\connection.py", line 2421, in connect
    return await connect_utils._connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<20 lines>...
    )
    ^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\asyncpg\connect_utils.py", line 1075, in _connect
    raise last_error or exceptions.TargetServerAttributeNotMatched(
    ...<2 lines>...
    )
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\asyncpg\connect_utils.py", line 1049, in _connect
    conn = await _connect_addr(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\asyncpg\connect_utils.py", line 886, in _connect_addr
    return await __connect_addr(params, True, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\asyncpg\connect_utils.py", line 931, in __connect_addr
    tr, pr = await connector
             ^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\asyncpg\connect_utils.py", line 802, in _create_ssl_connection
    tr, pr = await loop.create_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        host, port)
        ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 1122, in create_connection
    infos = await self._ensure_resolved(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        (host, port), family=family,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        type=socket.SOCK_STREAM, proto=proto, flags=flags, loop=self)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 1508, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                  proto=proto, flags=flags)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 939, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        None, getaddr_func, host, port, family, type, proto, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\socket.py", line 977, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed
INFO:     127.0.0.1:56660 - "POST /api/embed HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\fastapi\applications.py", line 1134, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\starlette\routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\starlette\routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\starlette\routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\fastapi\routing.py", line 124, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\fastapi\routing.py", line 110, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\fastapi\routing.py", line 390, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\fastapi\routing.py", line 289, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\app\api\embed.py", line 84, in create_embed_endpoint
    await crud_create_embed(session, embed_token=token, cypher_query=request.cypherQuery.strip(), expires_at=expires_at)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\app\db\crud.py", line 18, in create_embed
    await session.commit()
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 1000, in commit
    await greenlet_spawn(self.sync_session.commit)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2030, in commit
    trans.commit(_to_root=True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<string>", line 2, in commit
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1311, in commit
    self._prepare_impl()
    ~~~~~~~~~~~~~~~~~~^^
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1286, in _prepare_impl
    self.session.flush()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4331, in flush
    self._flush(objects)
    ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4466, in _flush
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4427, in _flush
    flush_context.execute()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.mapper,
        ^^^^^^^^^^^^
        uow.states_for_mapper_hierarchy(self.mapper, False, False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        uow,
        ^^^^
    )
    ^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 68, in save_obj
    ) in _organize_states_for_save(base_mapper, states, uowtransaction):
         ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 223, in _organize_states_for_save
    for state, dict_, mapper, connection in _connections_for_states(
                                            ~~~~~~~~~~~~~~~~~~~~~~~^
        base_mapper, uowtransaction, states
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ):
    ^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1759, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
  File "<string>", line 2, in connection
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1037, in connection
    return self._connection_for_bind(bind, execution_options)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1173, in _connection_for_bind
    conn = self._parent._connection_for_bind(
        bind, execution_options
    )
  File "<string>", line 2, in _connection_for_bind
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1187, in _connection_for_bind
    conn = bind.connect()
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3277, in connect
    return self._connection_cls(self)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 143, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3301, in raw_connection
    return self.pool.connect()
           ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 447, in connect
    return _ConnectionFairy._checkout(self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 711, in checkout
    rec = pool._do_get()
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 175, in _do_get
    return self._create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 388, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 673, in __init__
    self.__connect()
    ~~~~~~~~~~~~~~^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 899, in __connect
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 895, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\engine\create.py", line 661, in connect
    return dialect.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 629, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 955, in connect
    await_only(creator_fn(*arg, **kw)),
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\asyncpg\connection.py", line 2421, in connect
    return await connect_utils._connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<20 lines>...
    )
    ^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\asyncpg\connect_utils.py", line 1075, in _connect
    raise last_error or exceptions.TargetServerAttributeNotMatched(
    ...<2 lines>...
    )
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\asyncpg\connect_utils.py", line 1049, in _connect
    conn = await _connect_addr(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\asyncpg\connect_utils.py", line 886, in _connect_addr
    return await __connect_addr(params, True, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\asyncpg\connect_utils.py", line 931, in __connect_addr
    tr, pr = await connector
             ^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\hono-neo4j\fastapi-neo4j\.venv\Lib\site-packages\asyncpg\connect_utils.py", line 802, in _create_ssl_connection
    tr, pr = await loop.create_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        host, port)
        ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 1122, in create_connection
    infos = await self._ensure_resolved(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        (host, port), family=family,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        type=socket.SOCK_STREAM, proto=proto, flags=flags, loop=self)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 1508, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                  proto=proto, flags=flags)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 939, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        None, getaddr_func, host, port, family, type, proto, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\socket.py", line 977, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed
